### PR TITLE
Style update

### PR DESCRIPTION
**Pull request by kaarelkivisalu**
Sidebar is not working properly. Had some problems with displaying "autabel" and "koolid" but it might just be a problem with my local database.

### CODE REVIEW

**Comment by marko213** [comment]
Everything seems to be working fine for me, the problem is probably local.

For the sidebar, did you mean to make it appear "over" the main content rather than push the content to the right, or is there some other problem with it?

**Comment by marko213** [comment]
Also, the footer doesn't seem to work properly on the school profile page for some reason (the `float`?).

**Comment by kaarelkivisalu** [comment]
> Everything seems to be working fine for me, the problem is probably local.
> 
> For the sidebar, did you mean to make it appear "over" the main content rather than push the content to the right, or is there some other problem with it?

Pushing the main content to the right is ok for the computer size screen is ok. The opening of the sidebar is not smooth (a white part appears temporarily between the sidebar and the header).

Also for mobile devices, the sidebar looks ugly.

**Comment by marko213** [comment]
The white part temporarily appearing could be fixed by adding `transition: 0.5s` to `main` or `body` (in which case it's not really needed in `sidenav`, but maybe some dynamic changes should be without a transition?). This does however also move the text while the transition happens.

For mobile devices (through testing, for devices where the width is somewhere under 1000 px, landscape), the sidebar could be slightly narrower, but for smaller widths (under about 800 px, portrait), the "sidebar" could just hide the rest of the site while it's open. In this case the sidebar should also close when navigating to another page since otherwise the navigation might not be noticeable.

**Pull request merged**
